FROM node:8.9.4

RUN mkdir -p /home/Service

WORKDIR /home/Service

COPY assets/monitors/ /home/Service/assets/monitors
COPY src/app2.js /home/Service/src/app2.js
COPY package.json /home/Service

RUN npm cache verify \
    && npm config set registry https://registry.npm.taobao.org \
    && npm i

EXPOSE 8088

CMD ["npm", "run","koaStatic"]